### ISSUE TITLE
IO Error: Cannot open file

### ISSUE THREAD

**Issue by a-schommer** [tebeka/gadwall#1]
In my environment, gadwall always fails like:
```
C:\temp>python -m gadwall duck.db
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\gadwall.py", line 75, in <module>
    main()
  File "C:\Program Files\Python39\lib\site-packages\gadwall.py", line 68, in main
    cmd = Gadwall(args.filename.name)
  File "C:\Program Files\Python39\lib\site-packages\gadwall.py", line 22, in __init__
    self.conn = duckdb.connect(file_name)
RuntimeError: IO Error: Cannot open file "duck.db": The process cannot access the file because it is used by another process.
```
(Sorry, the last sentence may be wrong: it was in German, i translated it myself as i do not know how to force it to English)

I could fix this by two changes: I changed
```
    parser.add_argument('filename', type=FileType('r'))
    args = parser.parse_args()

    cmd = Gadwall(args.filename.name)
```
to
```
    parser.add_argument('filename')
    args = parser.parse_args()

    cmd = Gadwall(args.filename)
```
In fact, i wonder how the original code could work. But i did not find documentation of what argparse "returns" in case of type=FileType(). 

My environment:
Windows 10 21H2 (Build 19044.1586), 64bit
Python 3.9.6, 64bit
argparse-1.4.0
duckdb-0.3.2
gadwall-0.1.0

Kind regards,

Arnold

**Comment by tebeka** [comment]
Thanks @a-schommer for reporting. `args.filename.name` is a `str` just like your fix. 
Can you try something else? Add `args.filename.close()` before `cmd = ...`? and LMK if this works for you?

**Comment by a-schommer** [comment]
> Add `args.filename.close()` before `cmd = ...`? and LMK if this works for you?

Yes, that works, too. 
I sense this is better than my approach above because argparse still can check the file.
